### ISSUE TITLE
Tariffs

### ISSUE THREAD

**Issue by tmjo** [epaulsen/energytariff#11]
Contratulations on your good work here! I came over this integration by chance as I was considering to build something similar, I'd be happy to contribute here instead if necessary!

I just did the setup of the integration and I'm testing it out. If I understood correctly, the `price` in levels is supposed to be the monthly price for each capacity level, right?

I am aware that the different grid providers has different pricing models, although I guess most Norwegian companies follow more or less a similar template. In my case, my (Norwegian) grid provider charges me with a fixed capacity level per month which depends on the top three kWh/h that month (each max on different days). Additionally there is a variable energy cost which has only two different levels, one for day (06:00-22:00) and and for night + weekends (22:00 - 06:00 + whole weekend).

Not sure if I missed something, but I couldn't find how to add this variable cost. Would be great if this integration could also calculate for the energy part of the grid tariff. Is that something you would consider implementing?

Here's my tariffs as a reference:

![image](https://github.com/epaulsen/energytariff/assets/54450177/7d88a194-ad20-4e2f-b844-8834daaf45ad)

**Comment by epaulsen** [comment]
Sorry for the very late response.  Variable cost are not within scope of this service, as they vary between different grid suppliers.
Some grid suppliers have a simple cost depending upon time of day, others differenciate between business days and holidays, and winter/summer season.  So it would be difficult to add a common sensor for that.


However, it looks like you can create a rather simple sensor in your case, something like this:
```
sensor:
      # Grid energy cost
      - name: "Grid energy variable cost"
        unit_of_measurement: "NOK/kWh"
        icon: mdi:currency-usd
        state: >
          {% if now().hour >=6 and now().hour < 23 %}
              0.5205
          {%else%}
              0.4205
          {% endif %}
```
