### ISSUE TITLE
Use local time instead of UTC

### ISSUE THREAD

**Issue by epaulsen** [epaulsen/energytariff#5]
Three peak hours are at current stored using UTC time, this might lead to issues for calculating top three as consumption might end up on the wrong date.  It will also cause issues with monthly reset, as consumption in the last hours might be reported on next month, depending on the timezone of the HA installation.

Use local time helper from homeassistant.utils to convert UTC timestamp to local time.

**Comment by crackers81** [comment]
Nice :)
