### ISSUE TITLE
Average peak hour energy reset on new month?

### ISSUE THREAD

**Issue by laageide** [epaulsen/energytariff#6]
Should this sensor not reset when we enter a new month?

These max values is from the previous month

![image](https://user-images.githubusercontent.com/64701990/222833333-761ec110-6c7f-4732-af9b-1a0ddd05dd53.png)

**Comment by epaulsen** [comment]
@laageide , thank you for your kind words 😃 

This is indeed a (rather embarassing) bug.  Somehow the callback that should reset the attributes at monthly rollover did not get called as they should have been.  I will investigate and hopefully release a fix this evening.

**Comment by laageide** [comment]
@epaulsen : Nice work 👍 the reset function in developer tools works as described.
Thanks 😄
